DROP DATABASE IF EXISTS RESTAPI_CURSO;

CREATE DATABASE RESTAPI_CURSO;

USE RESTAPI_CURSO;

CREATE TABLE People (
	id INT NOT NULL AUTO_INCREMENT,
    address VARCHAR(255) NOT NULL,
    firstName VARCHAR(80) NOT NULL,
    lastName VARCHAR(80) NOT NULL,
    gender VARCHAR(15) NOT NULL,
    PRIMARY KEY (id)
);